name: Send Telegram Messages

on:
  schedule:
    # Cron for scheduling at 5:00 PM Malaysia Time (UTC+8), which is equivalent to 9:00 AM UTC
    - cron: '0 9 * * *'  # 5:00 PM MYT = 9:00 AM UTC
  workflow_dispatch:  # This allows manual run also

jobs:
  sendMessages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install telethon
          pip install pytz  # Install pytz library to handle timezones

      - name: Decode and save session file
        env:
          SESSION_BASE64: ${{ secrets.SESSION_BASE64 }}
        run: |
          # Decode the base64 session string into a file
          echo "$SESSION_BASE64" | base64 --decode > my_session.session

      - name: Run Python script
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          SESSION_NAME: my_session  # Use the decoded session file
        run: python post.py
