name: Send Telegram Messages

on:
  schedule:
    # Cron untuk menjadualkan pada 4:50 PM Malaysia Time (UTC+8), yang bersamaan dengan 8:50 AM UTC
    - cron: '50 8 * * *'  # 4:50 PM MYT = 8:50 AM UTC
  workflow_dispatch:  # Ini membolehkan manual run juga

jobs:
  sendMessages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: pip install telethon

      - name: Decode and save session file
        env:
          SESSION_BASE64: ${{ secrets.SESSION_BASE64 }}
        run: |
          echo "$SESSION_BASE64" | base64 --decode > my_session.session

      - name: Run Python script
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          SESSION_NAME: my_session  # Nama fail sesi
        run: python post.py
